### ISSUE TITLE
Memory Usage on Mac

### ISSUE THREAD

**Issue by Jack-Kemp** [tenpy/tenpy#262] opened 2023-06-06 19:01 UTC
Tenpy reports 1024 times peak memory usage on Mac than correct because in:

https://github.com/tenpy/tenpy/blob/main/tenpy/tools/process.py#L42

the line
`resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
`

returns in bytes rather than kilobytes on Mac, e.g. see https://stackoverflow.com/questions/938733/total-memory-used-by-python-process/7669482#7669482

**Comment by Jack-Kemp** [comment] 2023-06-06 19:08
Also for both Linux and Mac I believe this is *peak* memory usage, whereas the function claims *current* memory usage.

**Comment by Jakob-Unfried** [comment] 2023-06-06 22:00
Thanks for the report!

Regarding the units; it looks like you are correct....
Wow, what a wild function...

Would you like to make a PR and propose a fix?
If not, I can do it sometime soon.

@jhauschild 
Regarding current vs peak memory usage;
What do you think we should return here?
I.e. do we change the code to match the doc or vice versa?
I would think peak memory usage more useful than current usage, but I have never used `tenpy.tools.processes` this feature myself...

**Comment by jhauschild** [comment] 2023-06-07 08:01
It's true, it's the peak memory used so far by the python process.
From a practical point, there's also no way to change this with standard os process tools, since (the standard implementation of C-)Python doesn't return the memory to the system after usage, but keeps it for later usage.
Really, this is also what we *want* to regport, e.g. when DMRG logs info between sweeps (where this function is used at the moment), it makes sense to report the peak memory used (during Lanczos), not the current RAM usage.

I also wasn't aware that the unit isn't fixed, thanks for pointing it out!
@Jack-Kemp can you please that the issue is fixed now? Thanks!

**Comment by Jack-Kemp** [comment] 2023-06-07 17:24
@jhauschild The code looks correct to me. Unfortunately I was reporting the bug on behalf of a colleague who is now on holiday so I don't have access to a Mac to test...

Completely makes sense to me about peak vs current memory usage!

**Comment by Jakob-Unfried** [comment] 2023-06-07 17:26
i will test it tomorrow.

**Closed** 2023-06-13 08:36 UTC
Labels: bug
