### ISSUE TITLE
A problem with MPOEnvirnment

### ISSUE THREAD

**Issue by xiaohanyangggg** [tenpy/tenpy#402] opened 2024-04-16 14:37 UTC
**Describe the bug**
When the vumps branch was not merged into the main branch, I wrote the VUMPS algorithm myself and defined a sub-class of MPS named mps_Replica and they worked well. This class was defined to work as the uniform MPS class. Now I have updated physics-tenpy to v1.00 and I find when I use MPOEnvironment to calculate the environment it just doesn't work. This is because you have rewritten MPOEnvironment as a sub-class of the BaseEnvironment class and compatibility of the virtual bonds is checked every time you calculate the environments. However when I write my `mps_Replica` class I store AR's in the list `_B`, and AL's in the list `_BL`. As a result, when the compatibility of left and right environments `LP` and `RP` with the MPS outer virtual legs, they don't match with each other (since the outer_virtual_leg method just sees the virtual bonds of tensors in `_B` list). 

I think that adding a parameter to the MPOEnvironment class to tell it whether to check virtual bonds or not may make it more flexible. :) 

**Error traceback**
```
UserWarning: dropping `init_LP` with incompatible MPS legs
warnings.warn("dropping `init_LP` with incompatible MPS legs")
```

**Comment by xiaohanyangggg** [comment] 2024-04-16 15:04
Sorry. Maybe this issue should be moved to the `Enhancement` label. So please just help me delete it.

**Comment by Jakob-Unfried** [comment] 2024-05-05 10:31
I am not a fan of this pattern. Your class does not have proper subclass behavior, if the `_B` attribute does something else.
Notice how the `UniformMPS` class does not define the `MPS._B` attribute exactly for this reason.

Since we have a VUMPS implementation, I do not see a reason to change the codebase to support yours.

You can, of course override ``outer_virtual_legs`` to give the correct legs, which is exactly what we do in ``UniformMPS``.

**Comment by Jakob-Unfried** [comment] 2024-05-05 10:34
Duplicate of #403

**Closed by Jakob-Unfried** 2024-05-05 10:34 UTC
Labels: enhancement
