### ISSUE TITLE
small compatibility issue

### ISSUE THREAD

**Issue by doggenkit** [tenpy/tenpy#5] opened 2018-05-16 08:54 UTC
Hello,

Is it an intended feature that TenPy does not work at all under Windows? Your code works fine under my Linux distribution, but on my Windows (blasphemy, I know) machine nosetests yields 59 errors. One that pops up regularly is:

TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'

Using TenPy 0.3.0, Python 3.6.5, Numpy 1.14.2, Scipy 1.1.0

**Comment by jhauschild** [comment] 2018-05-17 09:47
I checked it this morning, the problem is that `tenpy.linalg.charges.QTYPE` is set to np.int_, which defaults on Windows to the 32-bit np.int32, while np.intp is np.int64, so the conversion between these two types is not save. As a quick fix, setting the QTYPE manually to np.int64 helps to avoid these errors.
After that, nostest on windows gives me a few other erros, which are not so substantial, DMRG & co work. (I didn't try to compile the Cython parts).
One problem is that loading LAPACK fails, but this is only a minor issue, since this only needed for a bugfix (due to the default svd returning a convergence error in some cases), which is not necessary any more with recent scipy versions.

**Comment by doggenkit** [comment] 2018-05-18 08:38
OK, thanks for checking! Sounds like a straightforward fix for your next commit.

**Comment by jhauschild** [comment] 2018-05-22 22:46
The lateset commit `f1f52fa` solves this in the better way: consistenltly use `QTYPE` only for charges, and `np.intp` for other (positive) indices. In that way, `QTYPE` being different from `np.intp` should no longer be a problem. I fixed it both in the python and Cython parts of `np_conserved`.
Any other serious issues on Windows?

**Comment by doggenkit** [comment] 2018-05-23 07:59
With the latest commit you are down to 10 errors (3 unique ones) with a few warnings - I'll leave you to judge whether they are serious issues. I add the output of `nosetests`:

[tenpy_errorlog.txt](https://github.com/tenpy/tenpy/files/2030017/tenpy_errorlog.txt)

**Comment by jhauschild** [comment] 2018-05-23 09:03
Thanks for the error log.
The first 4 Errors are in the network_contractor module, which is completely independent of DMRG/TEBD. Not sure, why this error occurs, looks like empty/0D arrays. I guess, for now, we can ignore it.
The next 3 Errors are due to the failure to import LAPACK. Again, you can ignore this, if you have scipy with a version >= 0.18.0. In the latest commit, I've handled this failure more gracefully and print a corresponding hint (it's now two 'F' instead of 3 'E' when running nosetests)
The remaining errors are caused by a wrong File path, using "/" instead of "\\" necessary for windows. This should be fixed now. Could you please check, that these errors dissapeared? Then we could close this issue.

**Comment by doggenkit** [comment] 2018-05-23 09:42
The latest commit still yields an error (total now 7 errors, 2 failures):

`AttributeError: 'SyntaxError' object has no attribute 'filename'`

There is a probably associated syntax error when running the examples, e.g. running d_dmrg.py returns:

```
    ../toycodes/tfi_exact.py
    ^
SyntaxError: invalid syntax
```

**Comment by jhauschild** [comment] 2018-05-24 09:17
You should now be down to 4 errors, 2 failures.
The problem with the examples was that I had used a symlink, which (by default) doesn't give a link on windows, but a file with the content of the link (i.e. the path, the link is pointing to.) 
The 4 errors of the network contractor module will probably be removed at some point in the future, but they are not windows specific. The 2 failures are expected on windows (due to missing LAPACK) and are not a problem anymore.

**Closed by jhauschild** 2018-05-24 09:17 UTC
