### ISSUE TITLE
Infinite DMRG for TFI in examples/d_dmrg.py might need psi.canonical_form()

### ISSUE THREAD

**Issue by tomohiro-soejima** [tenpy/tenpy#134] opened 2021-05-12 01:24 UTC
**Describe the bug**
I tried running `example_DMRG_tf_ising_infinite` from `examples/d_dmrg.py` with `g=0.6`. It prints the following `UserWarning` about unnormalized MPS:

```
E, psi, M = example_DMRG_tf_ising_infinite(0.6)
correlation length: 672098.5587682145
UserWarning: Correlation length: largest eigenvalue not one. Not in canonical form/normalized?
```

If I run `psi.canonical_form()`, this goes away.

```
psi.canonical_form()
psi.correlation_length()

0.8842916986002104
```
Should the script perhaps include a call to `psi.canonical_form()` to ensure the output psi is canonical?

**Minimal example or code extract**
It's taken from `d_dmrg.py`, but I include it here for completeness. 
```python
import numpy as np

from tenpy.networks.mps import MPS
from tenpy.models.tf_ising import TFIChain
from tenpy.models.spins import SpinModel
from tenpy.algorithms import dmrg

import logging
logging.basicConfig(level=logging.INFO)

def example_DMRG_tf_ising_infinite(g):
    print("infinite DMRG, transverse field Ising model")
    print("g={g:.2f}".format(g=g))
    model_params = dict(L=2, J=1., g=g, bc_MPS='infinite', conserve=None)
    M = TFIChain(model_params)
    product_state = ["up"] * M.lat.N_sites
    psi = MPS.from_product_state(M.lat.mps_sites(), product_state, bc=M.lat.bc_MPS)
    dmrg_params = {
        'mixer': True,  # setting this to True helps to escape local minima
        'trunc_params': {
            'chi_max': 30,
            'svd_min': 1.e-10
        },
        'max_E_err': 1.e-10,
    }
    # Sometimes, we want to call a 'DMRG engine' explicitly
    eng = dmrg.TwoSiteDMRGEngine(psi, M, dmrg_params)
    E, psi = eng.run()  # equivalent to dmrg.run() up to the return parameters.
    print("E = {E:.13f}".format(E=E))
    print("final bond dimensions: ", psi.chi)
    mag_x = np.mean(psi.expectation_value("Sigmax"))
    mag_z = np.mean(psi.expectation_value("Sigmaz"))
    print("<sigma_x> = {mag_x:.5f}".format(mag_x=mag_x))
    print("<sigma_z> = {mag_z:.5f}".format(mag_z=mag_z))
    print("correlation length:", psi.correlation_length())
    # compare to exact result
#     from tfi_exact import infinite_gs_energy
#     E_exact = infinite_gs_energy(1., g)
#     print("Analytic result: E (per site) = {E:.13f}".format(E=E_exact))
#     print("relative error: ", abs((E - E_exact) / E_exact))
    return E, psi, M

E, psi, M = example_DMRG_tf_ising_infinite(0.6)

psi.canonical_form()
psi.correlation_length()
```

**Comment by jhauschild** [comment] 2021-08-30 03:28
The resulting state actually is in canonical form, as you can verify with `psi.norm_test()`.
DMRG checks that at the end, and calls psi.canonical_form() otherwise.
However, here you get a "cat" state, a macroscopic superposition of `|+x>`  and `|-x>`. Calling `psi.canonical_form()` selects one of the two sectors, such that the subsequent `psi.correlation_length()` gives reasonable numbers (and log(2) less entanglement!).

It's a somewhat special case, because the TFI chain has so quickly decaying singular values that you represent even the cat state at that bond dimension with (almost) no truncation error. For virtually any other model, the truncation error actually helps to select one of the two degenerate ground states.

Interestingly, I also don't get the cat state if I use charge conservation in this case.

**Comment by Jakob-Unfried** [comment] 2023-05-15 11:07
If i run the example with the latest tenpy, the final DMRG state is not in canonical form and is subsequently converted;

```
In [2]: example_DMRG_tf_ising_infinite(.6)
infinite DMRG, transverse field Ising model
g=0.60
final DMRG state not in canonical form up to norm_tol_final=1.00e-10: norm_err=3.71e-07, calling psi.canonical_form()
canonical_form_infinite: project to significantly smaller chi
canonical_form_infinite: project to significantly smaller chi
canonical_form_infinite: project to significantly smaller chi
canonical_form_infinite: project to significantly smaller chi
E = -1.0922385835548
final bond dimensions:  [7, 7]
<sigma_x> = 0.94574
<sigma_z> = 0.31576
correlation length: 0.8843019050672333
Analytic result: E (per site) = -1.0922385835545
relative error:  2.470011580308288e-13
```

So I would say everything works as intended and I will close this.
If I am missing something, feel free to reopen =)

**Closed by Jakob-Unfried** 2023-05-15 11:07 UTC
Labels: bug
